name: CD

on:
  release:
    types: [created]
jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'maven'
          server-id: maven-central-release
          server-username: MVN_CENTRAL_USERNAME
          server-password: MVN_CENTRAL_PASSWORD
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
            gpg_private_key: ${{ secrets.MAVEN_SIGNING_KEY }}
            passphrase: ${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }}
      - name: Get tag
        id: get-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.0
          prefix: v
      - name: Publish to Maven
        run: mvn -P release -Dgpg.keyname=${{ secrets.GPG_KEY_NAME }} -Dgpg.passphrase=${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }} -Dversion=${{ steps.get-tag.outputs.tag }} deploy
        env:
          MVN_CENTRAL_USERNAME: ${{ secrets.MVN_CENTRAL_USERNAME }}
          MVN_CENTRAL_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Build site
        run: mvn site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        id: pages
        with:
          path: target/site/apidocs
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: pages
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
