name: Compute Changes

on:
  workflow_call:
    outputs:
      java:
        value: ${{ jobs.changed.outputs.java }}
      python:
        value: ${{ jobs.changed.outputs.python }}
      actions:
        value: ${{ jobs.changed.outputs.actions }}
      testdata:
        value: ${{ jobs.changed.outputs.testdata }}

jobs:
  changed:
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      python: ${{ steps.filter.outputs.python }}
      actions: ${{ steps.filter.outputs.actions }}
      testdata: ${{ steps.filter.outputs.testdata }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        show-progress: false
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: .github/path-filters.yml
        token: ${{ github.token }}
