name: CI (Python)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test-python:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
        working-directory: ./python
      - name: Test
        run: pytest tests/__init__.py
        working-directory: ./python
