name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test-java:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Test package
        run: mvn test
        working-directory: ./java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
