name: Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  changed:
    uses: ./.github/workflows/changed.yml

  java:
    needs: changed
    if: ${{ needs.changed.outputs.java == 'true' || needs.changed.outputs.actions == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Remove old content
        run: rm -rf ./site/java
      - name: Build site
        run: mvn site
        working-directory: ./java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Move files
        run: mv ./java/target/site ./site/java
      - name: Commit changes
        uses: iarekylew00t/verified-bot-commit@v1
        with:
          message: 'chore: Update site (Java)'
          files: |
            site/**/*

  python:
    needs: changed
    if: ${{ needs.changed.outputs.python == 'true' || needs.changed.outputs.actions == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
        working-directory: ./python
      - name: Remove old content
        run: |
          rm -rf ./site/python/main
          rm -rf ./site/python/tests
      - name: Build main site
        run: pdoc --html weftspace
        working-directory: ./python
      - name: Build test site
        run: pdoc -o htmltests/ --html tests
        working-directory: ./python
      - name: Move main files
        run: mv ./python/html ./site/python/main
      - name: Move test files
        run: mv ./python/htmltests ./site/python/tests
      - name: Commit changes
        uses: iarekylew00t/verified-bot-commit@v1
        with:
          message: 'chore: Update site (Python)'
          files: |
            site/**/*
